# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IsingProcess <- function(nSample, graph, thresholds, beta, responses) {
    .Call('_SparseIsingSampler_IsingProcess', PACKAGE = 'SparseIsingSampler', nSample, graph, thresholds, beta, responses)
}

IsingSamplerCpp <- function(n, graph, thresholds, beta, nIter, responses, exact, constrain) {
    .Call('_SparseIsingSampler_IsingSamplerCpp', PACKAGE = 'SparseIsingSampler', n, graph, thresholds, beta, nIter, responses, exact, constrain)
}

H <- function(J, s, h) {
    .Call('_SparseIsingSampler_H', PACKAGE = 'SparseIsingSampler', J, s, h)
}

f <- function(Y, J, h) {
    .Call('_SparseIsingSampler_f', PACKAGE = 'SparseIsingSampler', Y, J, h)
}

Hvec <- function(s, Theta, N) {
    .Call('_SparseIsingSampler_Hvec', PACKAGE = 'SparseIsingSampler', s, Theta, N)
}

expvalues <- function(x) {
    .Call('_SparseIsingSampler_expvalues', PACKAGE = 'SparseIsingSampler', x)
}

vec2Thresh <- function(vec, P) {
    .Call('_SparseIsingSampler_vec2Thresh', PACKAGE = 'SparseIsingSampler', vec, P)
}

vec2Graph <- function(vec, P) {
    .Call('_SparseIsingSampler_vec2Graph', PACKAGE = 'SparseIsingSampler', vec, P)
}

Broderick2013 <- function(x, M, T, nIter, responses) {
    .Call('_SparseIsingSampler_Broderick2013', PACKAGE = 'SparseIsingSampler', x, M, T, nIter, responses)
}

